const data = {
  products: [
    {
      _id: "1",
      title: "The Power Of Pivotin",
      auther: "Monica Ortega",
      image: "/images/Pivotin.jpg",
      price: 20,
      countInStock: 7,
      genre: "Drama",
      rating: 1.5,
      numReviews: 10,
      description: "How To Embrace Change And Create A Life You Love",
    },
    {
      _id: "2",
      title: "Psychology Of Money",
      auther: "Morgan Housel",
      image: "/images/Psychology.jpg",
      price: 10,
      countInStock: 22,
      genre: "Drama",
      rating: 4.0,
      numReviews: 10,
      description: "Timeless Lessons On Wealth, Greed and Happiness",
    },
    {
      _id: "3",
      title: "The Price Of Money",
      auther: "Rob Dix",
      image: "/images/Money.jpg",
      price: 15,
      countInStock: 19,
      genre: "Romance",
      rating: 2.0,
      numReviews: 20,
      description:
        "How To Prosper In A Financial World That's Rigged Against You",
    },
    {
      _id: "4",
      title: "Making Other People Rich",
      auther: "Ryan Sterling",
      image: "/images/Rich.jpg",
      price: 5,
      countInStock: 5,
      genre: "Romance",
      rating: 0.5,
      numReviews: 2,
      description: "Making Other People Rich And Happy",
    },
    {
      _id: "5",
      title: "Your're Making Other People Rich",
      auther: "Ryan Sterling",
      image: "/images/Rich.jpg",
      price: 5,
      countInStock: 5,
      genre: "Romance",
      rating: 4,
      numReviews: 2,
      description: "Making Other People Rich And Happy",
    },
  ],
};
export default data;
